"""create_hangout_tables

Revision ID: 67f32f0d0e63
Revises: 4c26267c5c93
Create Date: 2026-02-19 19:53:47.634904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f32f0d0e63'
down_revision: Union[str, Sequence[str], None] = '4c26267c5c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hangout_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Enum('restaurant', 'movie', 'sports', 'gaming', 'party', 'event', 'other', name='activity_type_enum'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', 'completed', name='post_status_enum'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hangout_posts_city'), 'hangout_posts', ['city'], unique=False)
    op.create_index(op.f('ix_hangout_posts_creator_id'), 'hangout_posts', ['creator_id'], unique=False)
    op.create_table('hangout_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('host', 'participant', name='participant_role_enum'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['hangout_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hangout_participants_post_id'), 'hangout_participants', ['post_id'], unique=False)
    op.create_index(op.f('ix_hangout_participants_user_id'), 'hangout_participants', ['user_id'], unique=False)
    op.create_table('hangout_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'cancelled', name='request_status_enum'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['hangout_posts.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hangout_requests_post_id'), 'hangout_requests', ['post_id'], unique=False)
    op.create_index(op.f('ix_hangout_requests_requester_id'), 'hangout_requests', ['requester_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hangout_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hangout_id'], ['hangout_posts.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_hangout_id'), 'reviews', ['hangout_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_hangout_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_hangout_requests_requester_id'), table_name='hangout_requests')
    op.drop_index(op.f('ix_hangout_requests_post_id'), table_name='hangout_requests')
    op.drop_table('hangout_requests')
    op.drop_index(op.f('ix_hangout_participants_user_id'), table_name='hangout_participants')
    op.drop_index(op.f('ix_hangout_participants_post_id'), table_name='hangout_participants')
    op.drop_table('hangout_participants')
    op.drop_index(op.f('ix_hangout_posts_creator_id'), table_name='hangout_posts')
    op.drop_index(op.f('ix_hangout_posts_city'), table_name='hangout_posts')
    op.drop_table('hangout_posts')
    # ### end Alembic commands ###
